# -*- coding: utf-8 -*-
"""Data Preprocessing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Oisot6ADPLlSLkiXnSKWweeShIVCjWDj
"""

import pandas as pd
import numpy as np
from tqdm import tqdm

df = pd.read_csv('validated.tsv', sep="\t")

# read the data frame
df.head()

inps = df["path"] #X
outs = df["sentence"] #Y

"""# ***Output Preprocessing***"""

def RMChars(y): # Remove the special charachters
    chars = [
    '!', '#', '$', '%', '&', '(', ')', '*', '+', ',', '-', '.', '/', ':',
    ';', '<', '=', '>', '?', '@', '[', '\\', ']', '^', '_', '`', '{', '|', '}',
    '~'
]
    return ''.join(ch for ch in y if ch not in chars)

# add tqdm progress bar
outs = np.array([RMChars(x) for x in tqdm(outs, desc='Removing special characters')]).astype(str)

outs

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.utils import pad_sequences

# Create a tokenizer and fit it to the sentences.
tokenizer = Tokenizer()
tokenizer.fit_on_texts(outs)

# Convert the sentences to sequences of integers using the tokenizer.
outs = tokenizer.texts_to_sequences(outs)

#print(outs)

#Pad sequences, having all same shape
outs = pad_sequences(outs)
#print(outs)

"""# ***Preprocess Input***"""

import librosa as lr
def LoadAudio(x):
    x, sr = lr.load(f"clips/{x}")
    x = lr.feature.mfcc(y=x, sr=sr, n_mfcc=13)
    try :
        x = np.mean(x)
        return x
    except ERROR as e:
        print(e)

# add tqdm progress bar
X = np.array([LoadAudio(x) for x in tqdm(inps, desc='Loading audio files')])

print(X)

# Save X as a .txt file
np.savetxt("X.txt", X)
np.savetxt("y.txt", y)